### PR TITLE
improved size functions flexibility and improved documentation

### PR DESCRIPTION
**Pull request by quintinm-dev**
Also removed error bars for size plots and added boxplot (as fmsb package for median C.I. is outdated)

### CODE REVIEW

**Comment by ttimbers** [comment]
@QMuncaster Looking better for the most part. I think we really want to avoid hard coding as much as possible so we can keep the reusability of our code high. What you have done for the plotting functions looks really good.

Before I merge this pull request, I'd like to see you make the `mean.size()` function more flexible. Right now it will break if your data frame doesn't have columns named `area, length, width, ID, strain, time`or `plate`. Can the function also have the input of a list of things to aggregate over,  a list of things to group by and the name of the column time.

**Comment by ttimbers** [comment]
Are you now done with the PR Quintin? Can I merge it?

**Comment by quintinm-dev** [comment]
Sorry not yet

**Comment by ttimbers** [comment]
no worries at all - just had time to look at it. Just let me know when it is done (no need to work on the weekend) :)

**Comment by quintinm-dev** [comment]
Dont merge this yet please; all the calls in main() work when I do them manually in RStudio, but whenever I try running the script from bash I get an error. Still trying to figure out what's happening.

**Comment by quintinm-dev** [comment]
Fixed - script works now

**Pull request merged**
